name: Hallucination Check

on:
  push:
    paths:
      - 'prompts/**'


jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI__API_KEY }}
      ARIZE_SPACE_ID: ${{ secrets.ARIZE_SPACE_ID }}
      ARIZE_API_KEY: ${{ secrets.ARIZE_API_KEY }}
      ARIZE_PROJECT_NAME: ${{ secrets.ARIZE_PROJECT_NAME }}
      ARIZE_DATASET_ID: ${{ secrets.ARIZE_DATASET_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: python ./benchmark.py
